# -*- coding: utf-8 -*-
"""Basics.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmB0X_rTWxFvR6_5Rw3keVwzZ1oJ1miz
"""

first_name = "Rayala" #string-type
print(first_name)

last_name = "Viswanath"
print() #New_Line

print(f"Hello {last_name}, Welcome") #Format specifier

age = 22
curr_year = 2025 #integer-type

birth_year = curr_year - age
print(birth_year)

product_price = 250.75 #Float-type
gst = 20.05
discount = 13.55

total_price = (product_price + gst) - discount
print(total_price)

user_id = "rayala07"
isValid = False #Boolean-type

if(isValid):
  print(f"{user_id} created successfully")
else:
  print(f"{user_id} already exists, try different user_id")

first_name = "Rayala"
age = 22
gst = 20.05
isValid = False

print(type(first_name)) #to get the data-type of a variable
print(type(age))
print(type(gst))
print(type(isValid))

#Explicit Typecasting
name = ""
age = 22
gpa = 7.7

name = bool(name) #Can be used to check whether user gave an input or left string field empty
print(name)

age = float(age)
print(age)

age = bool(age) #True for any number, False for 0
print(age)

gpa = int(gpa)
print(gpa)

#User Inputs
name = input("Enter your name: ")
age = int(input("Enter your age: "))

#If we want to performs operations on the integer input , you need to type cast the user input as by default it accepts as "string"
age = age - 2
print(age)


print(f"Hello {name}")
print(f"Your age is {age}")

#Round function
product_quantity = int(input("Enter total quantity: "))
product_price = float(input("Enter price of the product: "))

total_price = product_quantity * product_price

print(f"Total price = {round(total_price, 2)}") #To round the numbers after . to 2 decimals