# -*- coding: utf-8 -*-
"""Conditions/Strings

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmB0X_rTWxFvR6_5Rw3keVwzZ1oJ1miz
"""

# If-else conditions

# Python program that takes an integer input from user and checks:
input_number  = int(input("Enter number: "))

if input_number > 0:
  print("The number is +ve")
elif input_number < 0:
  print("The number is -ve")
else:
  print("Number is 0")

# Built-in Math functions
import math

x = 3.14
y = 5
z = 5

result = round(x) #round-off the float value
result = abs(y) #turns -ve to +ve
result = pow(y,3)
result = max(x,y,z)
result = min(x,y,z)
result = math.sqrt(y)
result = math.ceil(x)
result = math.floor(x)
print(math.pi)


print(result)

#Logical Operators -
# - and[both conditions should be true]
# - or[anyone conditions should be true to execute]
# - not[true to false , false to true]

#String methods

name = input("Enter your Full Name: ")
number = input("Enter your ph number: ")

result = len(name) #Considers _spaces too
result2 = name.find(" ") #Returns the first occurence only [follows string indexing 0 based]
result3 = name.rfind("a") #Returns the last occurence, returns -1 for both if not found
result4 = name.capitalize() #Capitalises the first letter only
result5 = name.upper()
result5 = name.lower()
result6 = name.isdigit() #returns true if only contains numbers
result7 = name.isalpha() #returns true if only contains alphabet [false for _spaces too]
result8 = number.count("-") #returns the frequency of the given input inside()
result9 = number.replace("-", " ") #(what_to_replace, with_what)


print(result9)

print(help(str)) #function that prints all methods and info. about the (data_type)