# -*- coding: utf-8 -*-
"""Date/Time

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmB0X_rTWxFvR6_5Rw3keVwzZ1oJ1miz
"""

# You can import the datetime module to use the methods of date/time and get and set according to needs
#Date Methods
import datetime

setDate = datetime.date(2024, 12, 25) #This method allows to set date according to own preference

dateToday = datetime.date.today() # This method gets today's date

print(setDate)
print(dateToday)

#Time methods

setTime = datetime.time(10, 15, 23) #Will return in a time format HH:MM:SS according to what has been set

currentTime = datetime.datetime.now() # Returns values like this - 2025-08-09 17:06:54.549720 all together, you can format it too

# Formatting the output of currentTime

currentTime = currentTime.strftime("%H:%M:%S  %d-%m-%Y") # We use the strinformattime() method with format specifier to format the display according to needs


print(setTime)
print(currentTime)

