# -*- coding: utf-8 -*-
"""Dictionaries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmB0X_rTWxFvR6_5Rw3keVwzZ1oJ1miz
"""

# Contact Book CLI
contacts = {}

inContactBook = True

while inContactBook:
  print("=== CONTACT BOOK MENU ===")
  print("1. Add Contact")
  print("2. View Contacts")
  print("3. Search Contact")
  print("4. Update Contact")
  print("5. Delete Contact")
  print("6. Exit")

  userChoice = int(input("Enter your choice: "))

  match userChoice:
    case 1:
      name = input("Enter name: ").lower()
      phone = input("Enter Phone number: ")
      if phone.isdigit():
        contacts[name] = phone
        print("Contact added successfully")
      else:
        print("Invalid Phone number input :(")
    case 2:
      print("=== CONTACTS ===")
      for name, phone in contacts.items():
        print(f"{name}: {phone}")
    case 3:
      name = input("Enter name to search:")
      convertedName = name.lower()
      if convertedName in contacts:
        print(f"{name}: {contacts[convertedName]}")
      else:
        print("Contact not found")
    case 4:
      name = input("Enter name to update number: ")
      convertedName = name.lower()
      if convertedName in contacts:
        phone = input("Enter new phone number: ")
        contacts[convertedName] = phone
        print("Contact updated successfully")
      else:
        print("Contact does not exist :(")
    case 5:
      name = input("Enter name to delete: ")
      convertedName = name.lower()
      if convertedName in contacts:
        del contacts[convertedName]
        print("Contact Deleted")
      else:
        print("Contact Does not exist !")
    case 6:
      print("Exit Success :)")
      inContactBook = False
    case _:
      print("Invalid Choice :(")

