# -*- coding: utf-8 -*-
"""File Handling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmB0X_rTWxFvR6_5Rw3keVwzZ1oJ1miz
"""

#Appending data into the file

txt_data = "Data appended successfully.."

file_path = "/content/output.txt"

with open(file_path, "a") as file:
  file.write("\n" + txt_data)

# "x" exclusive creation mode , will throw error if you create and write in a file
# Good practice to write "x" mode in a try-catch block

try:
  with open(file_path, "x") as file:
    file.write(txt_data)
except FileExistsError:
  print("File already exists")

# Writing data of a collection in a file -
# Only strings are writable so ,we need to iterate over each object of the collection list[], tuple(), set{} and write them into a file

student_names = ["Lucky", "Gana", "Pushpa", "Bunny", "Arya"]

file_path_2 = "names.txt"

with open(file_path_2, "w") as file:
  for each_student in student_names:
    file.write(each_student + "\n")

# Writing in a JSON file needs dictionary
import json

employee = {
    "name": "Rayala Viswanath",
    "age": 22,
    "position": "Software Engineer"
}

file_path_3 = "employee.json"

with open(file_path_3, "w") as file:
  json.dump(employee, file, indent=4)

# Writing in a .csv file (comma seperated values)
import csv

userData = [["Name", "Age", "userId"],
            ["Tony", 45, "tony.stark"],
            ["Peter", 25, "peter.parker"],
            ["Dr. Strange", 42, "stephen.strange"]]

file_path_4 = "users.csv"

with open(file_path_4, "w", newline="") as file:
  writer = csv.writer(file)
  for each_row in userData:
    writer.writerow(each_row)