# -*- coding: utf-8 -*-
"""Functions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmB0X_rTWxFvR6_5Rw3keVwzZ1oJ1miz
"""

# Functions in python - block of a code that can be reused multiple times but written only once.

def greeting():
  print("Hello user :)")

# greeting()
# greeting()

# Parametrised Functions - You can pass different parameters in it while calling each time

def addition(num1, num2):
  print(num1 + num2)

addition(10,20)
addition(100,200)

#Keyword Arguments- when you all this type of function you use an identifier so that you call the function in any order it will return with the order the function is defined in:

def generate_phone(country, area, number):
  return f"{country}-{area}{number}"

ph_num = generate_phone(country=91, number=67621580, area=89) #Increases code readability

print(ph_num)

# Default Arguments in Functions
# In this you can set a default value to the parameters , but difference is if you want to use some other value while calling the function you can pass you own value to in the parameter

def net_price(list_price, discount=0, tax=0.05):
  return list_price * (1 - discount) * ( 1 + tax)

print(net_price(500)) #Only list_price is passed other 2 are accepted by-default

# But you can pass other value as such when customer has a discount coupon
print(net_price(500,0.1))

# If you have one default and one normal parameter , remember to place the default parameter at the end

# *args = allows us to pass multiple non-keyword arguments without defining each vairable for it in the function
#Stored in tuple
def display_name(*fullName):
    for name in fullName:
      print(name, end=" ")

display_name("Mr.", "Rayala", "Viswanath")

# **kwargs = allows to pass multiple KEYWORD ARGUMENTS
# stored in dictionary as a key value pair

def print_address(**kwargs):
    print("Address: ")
    for key, value in kwargs.items():
      print(f"{value}")

print_address(street="Church street",
              qtr_no="DS/285/C",
              city="Adra",
              state="WB")

# We can also use both *args & **kwargs together according to need

def shipping_label(*userName, **address):  #-Make sure your **kwargs follows *args
    for name in userName:
        print(name, end=" ")

shipping_label("Mr.", "Rayala", "Viswanath",
               street="church road",
               qtr_no="DS/285/C",
               city="Adra",
               state="WB",
               pin="723121"
               )