# -*- coding: utf-8 -*-
"""Iterables

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmB0X_rTWxFvR6_5Rw3keVwzZ1oJ1miz
"""

# Iterables are objects/collections that can return its elements one at a time, allowing it to be iterated over in a loop

# List[] & Tuples() are iterable
numbers = [1,2,3,4,5] #(1,2,3,4,5)

# for number in reversed(numbers):
#   print(number, end=" ")

#Sets are also iterable but are not reversible :(

#Dictionary are also iterable with two vars- Keys and Values

my_dict = {"A": 1, "B": 2, "C": 3}

for value in my_dict.values():
  print(value) #Prints only values

for key in my_dict.keys():
  print(key) #Prints only keys

for key, value in my_dict.items():
  print(f"{key}: {value}") #Prints key: value pair of each element

