# -*- coding: utf-8 -*-
"""Loops

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmB0X_rTWxFvR6_5Rw3keVwzZ1oJ1miz
"""

#Loops
#Printing numbers 1 to 10

for i in range(1,11):
  print(i)

#Iterating through Characters of a string using a loop

name = input("Enter your name: ")

for i in name:
  print(i)

#While loop

num = 5

while num > 0:
  print(num)
  num -= 1

#Print numbers 1 to 20 but skip even numbers
for i in range(1,21):
  if i % 2 == 0:
    continue
  print(i)





