# -*- coding: utf-8 -*-
"""Conditions & Loops

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmB0X_rTWxFvR6_5Rw3keVwzZ1oJ1miz
"""

#Message Encryption Program
import random
import string

#To get all characters from the string module
chars = " "+ string.punctuation + string.digits + string.ascii_letters

#Converting them into a list of chars for mapping message with encrypted characters
chars = list(chars)

#Create a copy of the chars(list) in a keys variable that will help to convert the message into a encrypted msg code
keys = chars.copy()
#Random shuffle the key values each time so that encrypted message not same for every similar message
random.shuffle(keys)


#User-input
user_text = input("Enter message to encrypt: ")
cipher_text = ""


#Iterate over the user_text to create a encrypted message
for letter in user_text:
  index = chars.index(letter)
  cipher_text += keys[index]

print(f"User_message: {user_text}")
print(f"Encrypted_message: {cipher_text}")
print()
#Decrypting the message after it reaaches to the end user
endUserInterface = True

#Check a condition that is message has reached endUser and "endUserInterface = True" then decrypt the message
if endUserInterface:
  decrypted_text = ""
  for letter in cipher_text:
    index = keys.index(letter)
    decrypted_text += chars[index]
  print(f"Decrypted Text: {decrypted_text}")
else:
  print("Message not reached end user: Decryption Failed")

#Loops based basic to-do list program
running_TodoList = True

tasks = []



while running_TodoList:
  print("=== TO-DO LIST MENU ===")
  print("1. Add Task")
  print("2. View Tasks")
  print("3. Delete Task")
  print("4. EXIT")

  userChoice = input("Enter your choice [1/2/3]: ")

  match userChoice:
    case '1':
      print("You chose to Add task")
      task_input = input("Enter the task: ")
      tasks.append(task_input)
      print("Task added successfully!")
    case '2':
      print("You chose to View tasks")
      for index,each_task in enumerate(tasks, start=1):
        print(f"{index}. {each_task}")
    case '3':
      print("You chose to Delete task")
      for index,each_task in enumerate(tasks,start=1):
        print(f"{index}. {each_task}")
      print()
      task_delete = int(input("Enter the task number to delete task: "))
      tasks.pop(task_delete-1)
      print()
      print("Task deleted successfully!")
    case '4':
      print("Exiting the program...")
      running_TodoList = False
      print("Exit Success :)")
    case _:
      print("Invalid choice. Please try again.")
  print()