# -*- coding: utf-8 -*-
"""Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmB0X_rTWxFvR6_5Rw3keVwzZ1oJ1miz
"""

import pandas as pd

df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A","B","C"])

df.head() # To view the data, you need to use this command var.head()

df.head(2) # You can also set (num) till which you want to view the

df.tail(2) # var.tail(num) can be used to view bottom rows

# To view columns only
df.columns

# To view indices
df.index.tolist()

# You can also set custom indices
df_1 = pd.DataFrame([[9,8,7],[6,5,4],[3,2,1]], columns=['a','b','c'], index=['x','y','z'])

df_1.head()

# To get some aggregates on the data you can use .describe()
df.describe()

# Reading files
cofee = pd.read_csv('/content/coffee.csv')

cofee.head()

# Converting file types
# cofee.to_parquet()

# This will display only first-5 rows of the dataset
cofee.head()

# To view the full data of the file
cofee

# To get random view of the data and the number of the data
cofee.sample(6)

# You can also locate a single row or columns from the dataset
cofee.loc[0] #[row,row,row...] # You can also use slicing format

# cofee.iloc[] # Is position based

# Sorting
cofee.sort_values("Units Sold", ascending=False) # Be-default it will be asc = True,
#you can also pass more the one col. to sort





